name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest activities 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: 'https://github.com/michelderooij.atom,https://eightwone.com/feed/'
          max_post_count: '25'
          template: '- [$date $title]($url)<br />'
          date_format: 'isoDate'
          comment_tag_name: 'LATESTACTIVITY'
          remove_duplicates: 'true'
