name: Fetch iCal with Events
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-events-ics:
    name: Fetch iCAL with EXO events
    runs-on: ubuntu-latest
    permissions:
        issues: write
        pull-requests: write    
        repository-projects: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SECRET_PAT }}
      - name: Fetch ics file from Google calendar
        run: wget -qO- https://calendar.google.com/calendar/ical/b56cec28cd35e691394901c46fe425fd378b12d1a71e6dae8df524fa358f58e8%40group.calendar.google.com/public/basic.ics > events.ics
      - name: Check if file is updated
        id: check-updated
        run: |
          if [ "$(git ls-files --stage | grep events.ics | cut -f2)" != "$(git hash-object events.ics)" ]; then
            echo "{updated}={true}" >> $GITHUB_OUTPUT
          else
            echo "{updated}={false}" >> $GITHUB_OUTPUT
          fi
      - name: Add file and commit when changed
        if: ${{ steps.check-updated.outputs.updated }} == 'true'
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"
          git add events.ics
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
          
          
          
