name: Fetch iCal with Events
on:
  schedule:
    # Runs every 8 hours
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  update-events-ics:
    name: Fetch iCAL with EXO events
    runs-on: ubuntu-latest
    permissions:
        issues: write
        pull-requests: write    
        repository-projects: write
        contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SECRET_PAT }}
      - name: Fetch ics file from Google calendar
        run: wget -qO- https://calendar.google.com/calendar/ical/b56cec28cd35e691394901c46fe425fd378b12d1a71e6dae8df524fa358f58e8%40group.calendar.google.com/public/basic.ics > events.temp.ics
      - name: Process iCal file
        run: |
          sed -i 's/^PRODID:.*$/PRODID: EighTwOne Exchange Event Calendar/gm' events.temp.ics
          sed -i 's/google\.com/eightwone\.com/gm' events.temp.ics
      - name: Check if file is updated and git push if needed
        id: check-and-update
        run: |
          # Remove DTSTAMP (timestamp of retrieval) so we can compare on entries
          cp events.temp.ics hashme1
          cp events.ics hashme2
          sed -i 's/^DTSTAMP:.*$/DTSTAMP: Removed for comparison/gm' hashme1
          sed -i 's/^DTSTAMP:.*$/DTSTAMP: Removed for comparison/gm' hashme2
          if [ "$(git hash-object hashme1)" != "$(git hash-object hashme2)" ]; then
            mv events.temp.ics events.ics
            git config --global user.name "${{ vars.CI_COMMIT_AUTHOR }}"
            git config --global user.email "${{ vars.CI_COMMIT_EMAIL }}"
            git add events.ics
            git commit -m "Updated iCal file"
            git push https://x-access-token:${{ secrets.SECRET_PAT }}@github.com/${{ github.repository }}.git
          else
            rm events.temp.ics
          fi
          rm hashme1
          rm hashme2
