name: Fetch iCal with Events
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-events-ics:
    name: Fetch iCAL with EXO events
    runs-on: ubuntu-latest
    permissions:
        issues: write
        pull-requests: write    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch ics file from Google calendar
        run: curl https://calendar.google.com/calendar/ical/b56cec28cd35e691394901c46fe425fd378b12d1a71e6dae8df524fa358f58e8%40group.calendar.google.com/public/basic.ics -o /events.ics
    
